# Generated by Django 4.1.4 on 2022-12-28 04:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookings',
            new_name='Booking',
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.RenameModel(
            old_name='Seats',
            new_name='Screen',
        ),
        migrations.RenameModel(
            old_name='Screens',
            new_name='Seat',
        ),
        migrations.RenameModel(
            old_name='Shows',
            new_name='Show',
        ),
    ]
