# Generated by Django 4.1.4 on 2022-12-28 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_bookings_booking_rename_movies_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='name',
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='apis.seat'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='apis.screen'),
        ),
    ]
